### ISSUE TITLE
Code check with spotbugs plugin.

### ISSUE THREAD

**Issue by minyk** [bytrustu/StudySibaReborn#1]
Hello, @bytrustu  I found your project on https://cafe.naver.com/curiouscode, I cannot write a comment there, cause I don't introduce myself on the cafe yet. So I just open an issue on this repo. And I write this comment in English even if I'm a Korean. In this way, I train myself to use some English.

I think I'm an engineer more than a developer. I cannot write spring apps like you, but I have some knowledges for check/test/deploy a project. First of all, checking the code. As an engineer, I believe this: Some robotic code checks are really helpful, especially on the beginning phase of the project. So I like to use the `Spotbugs`(https://spotbugs.github.io/). Add `pom.xml` like this:
```xml
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
            <!-- SpotBugs Static Analysis -->
            <plugin>
                <groupId>com.github.spotbugs</groupId>
                <artifactId>spotbugs-maven-plugin</artifactId>
                <version>3.1.1</version>
                <configuration>
                    <effort>Max</effort>
                    <threshold>Low</threshold>
                    <failOnError>true</failOnError>
                    <plugins>
                        <plugin>
                            <groupId>com.h3xstream.findsecbugs</groupId>
                            <artifactId>findsecbugs-plugin</artifactId>
                            <version>LATEST</version> <!-- Auto-update to the latest stable -->
                        </plugin>
                    </plugins>
                </configuration>
            </plugin>
        </plugins>
    </build>
```

Then, execute analysis after compile. After analysis, open the spotbug gui:
```bash
$ mvn package
$ mvn spotbugs:spotbugs
$ mvn spotbugs:gui
```
You will see a GUI window of spotbugs. All the bugs detected in the code are sorted by `category, bug kind, ...`. Some of them are not bug in real(false detect). You just ignore these kinds of bug. 

Check those bugs and repair. Good luck.

**Comment by bytrustu** [comment]
Thank you for your good advice and attention.
I first heard about spotbugs through you.
I will search google and learn about this.
